# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/audio_equaliser_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zybo_audio_ctrl_0_0/design_1_zybo_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zybo_audio_ctrl_0_0 || ORIG_REF_NAME==design_1_zybo_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_1/design_1_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_1/design_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_bandpass_300_3kHz_0_0/design_1_FIR_bandpass_300_3kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_bandpass_300_3kHz_0_0 || ORIG_REF_NAME==design_1_FIR_bandpass_300_3kHz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_bandpass_3k_20kHz_0_0/design_1_FIR_bandpass_3k_20kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_bandpass_3k_20kHz_0_0 || ORIG_REF_NAME==design_1_FIR_bandpass_3k_20kHz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_bandpass_300_3kHz_Left_0/design_1_FIR_bandpass_300_3kHz_Left_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_bandpass_300_3kHz_Left_0 || ORIG_REF_NAME==design_1_FIR_bandpass_300_3kHz_Left_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_bandpass_3k_20kHz_Left_0/design_1_FIR_bandpass_3k_20kHz_Left_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_bandpass_3k_20kHz_Left_0 || ORIG_REF_NAME==design_1_FIR_bandpass_3k_20kHz_Left_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_lowpass_300Hz_0_0/design_1_FIR_lowpass_300Hz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_lowpass_300Hz_0_0 || ORIG_REF_NAME==design_1_FIR_lowpass_300Hz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FIR_lowpass_300Hz_Left_0/design_1_FIR_lowpass_300Hz_Left_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FIR_lowpass_300Hz_Left_0 || ORIG_REF_NAME==design_1_FIR_lowpass_300Hz_Left_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Xilinx/projects/012_AUDIO_EQUALISER/012_AUDIO_EQUALISER.gen/sources_1/bd/design_1/design_1_ooc.xdc
