// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FIR_bandpass_300_3kHz_FIR_bandpass_300_3kHz,hls_ip_2021_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.718063,HLS_SYN_LAT=158,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=285,HLS_SYN_LUT=407,HLS_VERSION=2021_2}" *)

module FIR_bandpass_300_3kHz (
        ap_local_block,
        ap_clk,
        ap_rst_n,
        s_axi_fir_io_AWVALID,
        s_axi_fir_io_AWREADY,
        s_axi_fir_io_AWADDR,
        s_axi_fir_io_WVALID,
        s_axi_fir_io_WREADY,
        s_axi_fir_io_WDATA,
        s_axi_fir_io_WSTRB,
        s_axi_fir_io_ARVALID,
        s_axi_fir_io_ARREADY,
        s_axi_fir_io_ARADDR,
        s_axi_fir_io_RVALID,
        s_axi_fir_io_RREADY,
        s_axi_fir_io_RDATA,
        s_axi_fir_io_RRESP,
        s_axi_fir_io_BVALID,
        s_axi_fir_io_BREADY,
        s_axi_fir_io_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_FIR_IO_DATA_WIDTH = 32;
parameter    C_S_AXI_FIR_IO_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_FIR_IO_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

output   ap_local_block;
input   ap_clk;
input   ap_rst_n;
input   s_axi_fir_io_AWVALID;
output   s_axi_fir_io_AWREADY;
input  [C_S_AXI_FIR_IO_ADDR_WIDTH - 1:0] s_axi_fir_io_AWADDR;
input   s_axi_fir_io_WVALID;
output   s_axi_fir_io_WREADY;
input  [C_S_AXI_FIR_IO_DATA_WIDTH - 1:0] s_axi_fir_io_WDATA;
input  [C_S_AXI_FIR_IO_WSTRB_WIDTH - 1:0] s_axi_fir_io_WSTRB;
input   s_axi_fir_io_ARVALID;
output   s_axi_fir_io_ARREADY;
input  [C_S_AXI_FIR_IO_ADDR_WIDTH - 1:0] s_axi_fir_io_ARADDR;
output   s_axi_fir_io_RVALID;
input   s_axi_fir_io_RREADY;
output  [C_S_AXI_FIR_IO_DATA_WIDTH - 1:0] s_axi_fir_io_RDATA;
output  [1:0] s_axi_fir_io_RRESP;
output   s_axi_fir_io_BVALID;
input   s_axi_fir_io_BREADY;
output  [1:0] s_axi_fir_io_BRESP;
output   interrupt;

wire   [0:0] ap_local_deadlock;
 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] y;
reg    y_ap_vld;
wire   [15:0] x;
reg   [7:0] shift_reg_address0;
reg    shift_reg_ce0;
reg    shift_reg_we0;
reg   [15:0] shift_reg_d0;
wire   [15:0] shift_reg_q0;
wire   [15:0] shift_reg_q1;
reg   [15:0] shift_reg_load_reg_180;
wire    ap_CS_fsm_state2;
wire   [20:0] acc_fu_113_p2;
reg   [20:0] acc_reg_186;
wire    ap_CS_fsm_state3;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_done;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_idle;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_ready;
wire   [30:0] grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out_ap_vld;
wire   [7:0] grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address0;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce0;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_we0;
wire   [15:0] grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_d0;
wire   [7:0] grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address1;
wire    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce1;
reg    grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [30:0] acc_01_loc_fu_56;
wire    ap_CS_fsm_state5;
wire   [19:0] shl_ln_fu_91_p3;
wire   [17:0] shl_ln44_1_fu_102_p3;
wire  signed [20:0] sext_ln44_1_fu_109_p1;
wire  signed [20:0] sext_ln44_fu_98_p1;
wire   [19:0] shl_ln1_fu_123_p3;
wire   [17:0] shl_ln55_1_fu_135_p3;
wire  signed [20:0] sext_ln55_1_fu_143_p1;
wire  signed [20:0] sext_ln55_fu_131_p1;
wire   [20:0] sub_ln55_fu_147_p2;
wire  signed [30:0] sext_ln55_2_fu_153_p1;
wire   [30:0] acc_3_fu_157_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg = 1'b0;
end

FIR_bandpass_300_3kHz_shift_reg_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 150 ),
    .AddressWidth( 8 ))
shift_reg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(shift_reg_address0),
    .ce0(shift_reg_ce0),
    .we0(shift_reg_we0),
    .d0(shift_reg_d0),
    .q0(shift_reg_q0),
    .address1(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address1),
    .ce1(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce1),
    .q1(shift_reg_q1)
);

FIR_bandpass_300_3kHz_FIR_bandpass_300_3kHz_Pipeline_loop grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start),
    .ap_done(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_done),
    .ap_idle(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_idle),
    .ap_ready(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_ready),
    .sext_ln38(acc_reg_186),
    .acc_01_out(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out),
    .acc_01_out_ap_vld(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out_ap_vld),
    .shift_reg_address0(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address0),
    .shift_reg_ce0(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce0),
    .shift_reg_we0(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_we0),
    .shift_reg_d0(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_d0),
    .shift_reg_address1(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address1),
    .shift_reg_ce1(grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce1),
    .shift_reg_q1(shift_reg_q1)
);

FIR_bandpass_300_3kHz_fir_io_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_FIR_IO_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_FIR_IO_DATA_WIDTH ))
fir_io_s_axi_U(
    .AWVALID(s_axi_fir_io_AWVALID),
    .AWREADY(s_axi_fir_io_AWREADY),
    .AWADDR(s_axi_fir_io_AWADDR),
    .WVALID(s_axi_fir_io_WVALID),
    .WREADY(s_axi_fir_io_WREADY),
    .WDATA(s_axi_fir_io_WDATA),
    .WSTRB(s_axi_fir_io_WSTRB),
    .ARVALID(s_axi_fir_io_ARVALID),
    .ARREADY(s_axi_fir_io_ARREADY),
    .ARADDR(s_axi_fir_io_ARADDR),
    .RVALID(s_axi_fir_io_RVALID),
    .RREADY(s_axi_fir_io_RREADY),
    .RDATA(s_axi_fir_io_RDATA),
    .RRESP(s_axi_fir_io_RRESP),
    .BVALID(s_axi_fir_io_BVALID),
    .BREADY(s_axi_fir_io_BREADY),
    .BRESP(s_axi_fir_io_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .y(y),
    .y_ap_vld(y_ap_vld),
    .x(x),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_local_deadlock(ap_local_deadlock)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_ready == 1'b1)) begin
            grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_01_loc_fu_56 <= grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_acc_01_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_reg_186[20 : 2] <= acc_fu_113_p2[20 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        shift_reg_load_reg_180 <= shift_reg_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_address0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        shift_reg_address0 = 8'd149;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        shift_reg_address0 = grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_address0;
    end else begin
        shift_reg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        shift_reg_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        shift_reg_ce0 = grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_ce0;
    end else begin
        shift_reg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_d0 = x;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        shift_reg_d0 = grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_d0;
    end else begin
        shift_reg_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        shift_reg_we0 = grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_shift_reg_we0;
    end else begin
        shift_reg_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_3_fu_157_p2 = ($signed(acc_01_loc_fu_56) + $signed(sext_ln55_2_fu_153_p1));

assign acc_fu_113_p2 = ($signed(sext_ln44_1_fu_109_p1) - $signed(sext_ln44_fu_98_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'd0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start = grp_FIR_bandpass_300_3kHz_Pipeline_loop_fu_81_ap_start_reg;

assign sext_ln44_1_fu_109_p1 = $signed(shl_ln44_1_fu_102_p3);

assign sext_ln44_fu_98_p1 = $signed(shl_ln_fu_91_p3);

assign sext_ln55_1_fu_143_p1 = $signed(shl_ln55_1_fu_135_p3);

assign sext_ln55_2_fu_153_p1 = $signed(sub_ln55_fu_147_p2);

assign sext_ln55_fu_131_p1 = $signed(shl_ln1_fu_123_p3);

assign shl_ln1_fu_123_p3 = {{x}, {4'd0}};

assign shl_ln44_1_fu_102_p3 = {{shift_reg_load_reg_180}, {2'd0}};

assign shl_ln55_1_fu_135_p3 = {{x}, {2'd0}};

assign shl_ln_fu_91_p3 = {{shift_reg_load_reg_180}, {4'd0}};

assign sub_ln55_fu_147_p2 = ($signed(sext_ln55_1_fu_143_p1) - $signed(sext_ln55_fu_131_p1));

assign y = {{acc_3_fu_157_p2[30:15]}};

always @ (posedge ap_clk) begin
    acc_reg_186[1:0] <= 2'b00;
end

endmodule //FIR_bandpass_300_3kHz
